version: '3.8'

services:
  user-db:
    image: postgres:15-alpine
    container_name: user_db
    environment:
      POSTGRES_DB: online_microservice_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:15-alpine
    container_name: order_db
    environment:
      POSTGRES_DB: online_microservice_order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./docs:/app:ro

volumes:
  user_db_data:
  order_db_data:
